export default {
	testEnvironment: "node",
	extensionsToTreatAsEsm: [".ts"],
	moduleNameMapper: {
		"^@domain/(.*)\\.js$": "<rootDir>/src/domain/$1",
		"^@application/(.*)\\.js$": "<rootDir>/src/application/$1",
		"^@dtos/(.*)\\.js$": "<rootDir>/src/application/dtos/$1",
		"^@ports/(.*)\\.js$": "<rootDir>/src/application/ports/$1",
		"^@use-cases/(.*)\\.js$": "<rootDir>/src/application/use-cases/$1",
		"^@infrastructure/(.*)\\.js$": "<rootDir>/src/infrastructure/$1",
		"^@interfaces/(.*)\\.js$": "<rootDir>/src/interfaces/$1",
		"^@config/(.*)\\.js$": "<rootDir>/src/config/$1",
		"^@di/(.*)\\.js$": "<rootDir>/src/config/di/$1",
		"^@modules/(.*)\\.js$": "<rootDir>/src/modules/$1",
		"^@domain/(.*)$": "<rootDir>/src/domain/$1",
		"^@application/(.*)$": "<rootDir>/src/application/$1",
		"^@dtos/(.*)$": "<rootDir>/src/application/dtos/$1",
		"^@ports/(.*)$": "<rootDir>/src/application/ports/$1",
		"^@use-cases/(.*)$": "<rootDir>/src/application/use-cases/$1",
		"^@infrastructure/(.*)$": "<rootDir>/src/infrastructure/$1",
		"^@interfaces/(.*)$": "<rootDir>/src/interfaces/$1",
		"^@config/(.*)$": "<rootDir>/src/config/$1",
		"^@di/(.*)$": "<rootDir>/src/config/di/$1",
		"^@modules/(.*)$": "<rootDir>/src/modules/$1",
		"^(\\.{1,2}/.*)\\.js$": "$1",
	},
	transform: {
		"^.+\\.(t|j)sx?$": "@swc/jest",
	},
};
