export enum BullMQEvent {
	CONNECT = "connect",
	READY = "ready",
	ERROR = "error",
	CLOSE = "close",
	WAITING = "waiting",
	ACTIVE = "active",
	COMPLETED = "completed",
	FAILED = "failed",
	PROGRESS = "progress",
	STALLED = "stalled",
	PAUSED = "paused",
	RESUMED = "resumed",
	DRAINED = "drained",
	CLEANED = "cleaned",
	CLOSING = "closing",
	CLOSED = "closed",
}
