
export enum errorCodes {
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
    INVALID_OTP = "INVALID_OTP",
    OTP_EXPIRED = "OTP_EXPIRED",
    RESET_PASSWORD_FAILED = "RESET_PASSWORD_FAILED",
    USER_NOT_FOUND = "USER_NOT_FOUND"
}